services:
  homepage:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    volumes:
      - ..:/homepage:cached
      - node_modules:/homepage/node_modules
    command: "sleep infinity"

volumes:
  node_modules:
